# ----------------------------------------------------------------------------
# Copyright (c) 2026, QIIME 2 development team.
#
# Distributed under the terms of the GPL-3.0 license.
#
# The full license is in the file LICENSE, distributed with this software.
# ----------------------------------------------------------------------------

from qiime2.plugin import Bool, Citations, Choices, Int, Plugin, Range, Str, Threads
from q2_types.feature_table import FeatureTable, Frequency
from q2_types.genome_data import DNASequence, GenomeData, Loci
from q2_types.per_sample_sequences import (
    AlignmentMap,
    JoinedSequencesWithQuality,
    PairedEndSequencesWithQuality,
    SequencesWithQuality,
)
from q2_types.sample_data import SampleData
from q2_subread import __version__
from q2_subread._methods import align_reads, feature_counts

citations = Citations.load("citations.bib", package="q2_subread")

plugin = Plugin(
    name="subread",
    version=__version__,
    website="https://github.com/mziemski/q2-subread",
    package="q2_subread",
    description="QIIME 2 plugin for wrapping the Subread software package.",
    short_description="Subread integration for QIIME 2.",
    # The plugin-level citation of 'Caporaso-Bolyen-2024' is provided as
    # an example. You can replace this with citations to other references
    # in citations.bib.
    citations=[citations['Caporaso-Bolyen-2024']]
)

plugin.methods.register_function(
    function=align_reads,
    inputs={
        "reads": SampleData[
            SequencesWithQuality
            | JoinedSequencesWithQuality
            | PairedEndSequencesWithQuality
        ],
        "reference_sequences": GenomeData[DNASequence],
    },
    parameters={
        "threads": Threads,
        "indels": Int % Range(0, None),
        "multi_mapping": Bool,
        "max_alignments": Int % Range(1, None),
        "minimum_fragment_length": Int % Range(0, None),
        "maximum_fragment_length": Int % Range(1, None),
    },
    outputs=[("alignment_maps", SampleData[AlignmentMap])],
    input_descriptions={
        "reads": (
            "Single-end, joined, or paired-end demultiplexed reads to align "
            "with Subread."
        ),
        "reference_sequences": (
            "Reference genome FASTA sequences used to build a temporary "
            "Subread index."
        ),
    },
    parameter_descriptions={
        "threads": "Number of worker threads to pass to subread-align.",
        "indels": (
            "Maximum indel size to detect, passed to subread-align via -I."
        ),
        "multi_mapping": (
            "Report multiple mapping locations instead of only uniquely "
            "mapped reads."
        ),
        "max_alignments": (
            "Maximum number of reported alignments per read when "
            "multi-mapping output is enabled."
        ),
        "minimum_fragment_length": (
            "Minimum expected fragment length for paired-end reads, passed "
            "to subread-align via -d. Ignored for single-end or joined reads."
        ),
        "maximum_fragment_length": (
            "Maximum expected fragment length for paired-end reads, passed "
            "to subread-align via -D. Ignored for single-end or joined reads."
        ),
    },
    output_descriptions={
        "alignment_maps": "Per-sample BAM alignment files generated by Subread."
    },
    name="Align reads",
    description=(
        "Build a temporary Subread index from reference genome sequences and "
        "align single-end, joined, or paired-end reads."
    ),
    citations=[citations["Liao-2013-Subread"]],
)

plugin.methods.register_function(
    function=feature_counts,
    inputs={
        "alignment_maps": SampleData[AlignmentMap],
        "loci": GenomeData[Loci],
    },
    parameters={
        "feature_type": Str,
        "id_attribute": Str,
        "strand_mode": Str % Choices({"unstranded", "forward", "reverse"}),
        "threads": Threads,
        "paired_end": Bool,
    },
    outputs=[("feature_table", FeatureTable[Frequency])],
    input_descriptions={
        "alignment_maps": (
            "Sample-wise BAM alignment maps to quantify with featureCounts."
        ),
        "loci": (
            "Genome loci annotations in GFF3 format describing the features "
            "to count."
        ),
    },
    parameter_descriptions={
        "feature_type": (
            "Feature type from the GFF3 annotation to count, passed to "
            "featureCounts via -t."
        ),
        "id_attribute": (
            "Annotation attribute used to group records into output features, "
            "passed to featureCounts via -g."
        ),
        "strand_mode": (
            "Library strandedness for counting: unstranded, forward, or "
            "reverse."
        ),
        "threads": "Number of worker threads to pass to featureCounts.",
        "paired_end": (
            "Treat the BAM inputs as paired-end alignments and pass -p to "
            "featureCounts."
        ),
    },
    output_descriptions={
        "feature_table": (
            "A feature table of counts reported by featureCounts, with genes "
            "or other annotated features as observations and samples as "
            "columns."
        ),
    },
    name="Count annotated features",
    description=(
        "Run Subread featureCounts on BAM alignment maps and GFF3 loci "
        "annotations to generate a feature count table."
    ),
    citations=[citations["Liao-2014-featureCounts"]],
)
