# ----------------------------------------------------------------------------
# Copyright (c) 2026, QIIME 2 development team.
#
# Distributed under the terms of the GPL-3.0 license.
#
# The full license is in the file LICENSE, distributed with this software.
# ----------------------------------------------------------------------------
from q2_types.feature_data import FeatureData, Sequence
from q2_types.feature_table import FeatureTable, Frequency
from q2_types.genome_data import GenomeData, Loci
from q2_types.per_sample_sequences import (
    AlignmentMap,
    PairedEndSequencesWithQuality,
    SequencesWithQuality,
)
from q2_types.sample_data import SampleData
from rachis.plugin import (
    Bool,
    Citations,
    Choices,
    Int,
    Plugin,
    Range,
    Str,
    Threads,
)

from q2_subread import __version__
from q2_subread.feature_counts import count_features
from q2_subread.mapping import map_reads
from q2_subread.indexing import build_index
from q2_subread._types import SubreadIndex, SubreadIndexDirFmt

citations = Citations.load("citations.bib", package="q2_subread")

plugin = Plugin(
    name="subread",
    version=__version__,
    website="https://github.com/bokulich-lab/q2-subread",
    package="q2_subread",
    description="QIIME 2 plugin for read mapping and analysis with Subread.",
    short_description="Subread integration for QIIME 2.",
    citations=[citations["Liao-2014-featureCounts"], citations["Liao-2013-Subread"]],
)


plugin.methods.register_function(
    function=build_index,
    inputs={"reference": FeatureData[Sequence]},
    parameters={
        "full": Bool,
        "block": Bool,
        "memory": Int % Range(1, None),
        "threshold": Int % Range(1, None),
        "color": Bool,
    },
    outputs=[("index", SubreadIndex)],
    input_descriptions={
        "reference": ("Reference sequences used to build a Subread index."),
    },
    parameter_descriptions={
        "full": "Build a full index for the reference.",
        "block": "Create one block of index.",
        "memory": "Size of requested memory (RAM) in megabytes.",
        "threshold": (
            "Threshold for removing uninformative subreads "
            "(highly repetitive 16mers in the reference)."
        ),
        "color": "Build a color-space index.",
    },
    output_descriptions={
        "index": "Subread index built from the input reference sequences.",
    },
    name="Build Subread index.",
    description="Build a reusable Subread index from reference sequences.",
    citations=[citations["Liao-2013-Subread"]],
)

plugin.methods.register_function(
    function=map_reads,
    inputs={
        "reads": SampleData[SequencesWithQuality | PairedEndSequencesWithQuality],
        "reference_index": SubreadIndex,
    },
    parameters={
        "threads": Threads,
        "indels": Int % Range(0, None),
        "multi_mapping": Bool,
        "max_alignments": Int % Range(1, None),
        "minimum_fragment_length": Int % Range(0, None),
        "maximum_fragment_length": Int % Range(1, None),
        "experiment_type": Str % Choices({"rna-seq", "dna-seq"}),
    },
    outputs=[("alignment_maps", SampleData[AlignmentMap])],
    input_descriptions={
        "reads": (
            "Single-end or paired-end demultiplexed reads to align with "
            "subread-align."
        ),
        "reference_index": (
            "Pre-built Subread index artifact used for read alignment."
        ),
    },
    parameter_descriptions={
        "threads": "Number of worker threads to pass to subread-align.",
        "indels": "Maximum indel size to detect, passed to subread-align.",
        "multi_mapping": (
            "Report multiple mapping locations instead of only uniquely "
            "mapped reads."
        ),
        "max_alignments": (
            "Maximum number of reported alignments per read when "
            "multi-mapping output is enabled."
        ),
        "minimum_fragment_length": (
            "Minimum expected fragment length for paired-end reads, passed "
            "to subread-align. Ignored for single-end reads."
        ),
        "maximum_fragment_length": (
            "Maximum expected fragment length for paired-end reads, passed "
            "to subread-align. Ignored for single-end reads."
        ),
        "experiment_type": (
            "Type of sequencing experiment: RNA-seq or genomic DNA-seq."
        ),
    },
    output_descriptions={
        "alignment_maps": "Per-sample BAM alignment files generated by Subread.",
    },
    name="Align reads to a Subread index.",
    description=(
        "Align single-end or paired-end reads against a pre-built Subread " "index."
    ),
    citations=[citations["Liao-2013-Subread"]],
)

plugin.methods.register_function(
    function=count_features,
    inputs={
        "alignment_maps": SampleData[AlignmentMap],
        "loci": GenomeData[Loci],
    },
    parameters={
        "feature_type": Str,
        "id_attribute": Str,
        "strand_mode": Str % Choices({"unstranded", "forward", "reverse"}),
        "threads": Threads,
        "paired_end": Bool,
        "reference_id": Str,
    },
    outputs=[("feature_table", FeatureTable[Frequency])],
    input_descriptions={
        "alignment_maps": (
            "Sample-wise BAM alignment maps to quantify with featureCounts."
        ),
        "loci": ("Genome loci annotations describing the features to count."),
    },
    parameter_descriptions={
        "feature_type": (
            "Feature type from the GFF3 annotation to count, passed to "
            "featureCounts."
        ),
        "id_attribute": (
            "Annotation attribute used to group records into output features, "
            "passed to featureCounts."
        ),
        "strand_mode": (
            "Library strandedness for counting: unstranded, forward, or reverse."
        ),
        "threads": "Number of worker threads to pass to featureCounts.",
        "paired_end": (
            "Treat the BAM inputs as paired-end alignments and pass -p to "
            "featureCounts."
        ),
        "reference_id": "ID of the reference to use for feature counting.",
    },
    output_descriptions={
        "feature_table": "A feature table of counts reported by featureCounts.",
    },
    name="Count annotated features.",
    description=(
        "Run Subread featureCounts on BAM alignment maps and GFF3 loci "
        "annotations to generate a feature count table."
    ),
    citations=[citations["Liao-2014-featureCounts"]],
)


plugin.register_semantic_types(SubreadIndex)
plugin.register_formats(SubreadIndexDirFmt)
plugin.register_semantic_type_to_format(
    SubreadIndex, artifact_format=SubreadIndexDirFmt
)
